### ISSUE TITLE
Cannot compile using smpcc

### ISSUE THREAD

**Issue by kareekij** [tjim/smpcc#7]
Got the error, when try to compile foo.c I try by using both Vagrant and Docker approaches on both Linux and MacOS. The error happen when I hit 'smpcc foo.c'. The message were

By using Vagrant =================== 
sh: cilly: command not found
Fatal error: exception Failure("Error: cilly failed with exit code 127")

By using Docker ==================== 
Parse error at line 14 character 5, the lexeme is !
Fatal error: exception Failure("Giving up")

**Comment by tjim** [comment]
Hi. Kind of hard to tell since you do not include foo.c with your report :-). I'll need to see that.

Also, I should say that the project is not really ready for external use, though you are welcome to follow along. There should be lots of changes in the next month.

**Comment by kareekij** [comment]
Actually, my foo.c is as same as in your instruction. 

int main() {
    return 5;
}

I try to install all the components and try to compile the code with smpcc, but I was hung at that step.

**Comment by tjim** [comment]
OK, just gave that a try myself and it is working for me. I am using the docker method on a Mac.

**Comment by tjim** [comment]
It's an LLVM issue (format of LLVM assembly has changed). Will try to fix.

**Comment by tjim** [comment]
The example foo.c should work now. There have been a lot of changes in LLVM so there will probably be other bugs to fix.
